### ISSUE TITLE
JMockit中文网, 在网站上发现几处文案错误

### ISSUE THREAD

**Issue by gshine** [hzdavid/jmockit.cn#3]
http://jmockit.cn/showArticle.htm?id=10 这个页面有几处文案错误：
1）该页面的第一段示例代码，【times/minTimes/maxTime】  ==》最后的那个应该是maxTimes。出现两次。
2）该页面的第一段示例代码，【还可以再写new一个Verifications，只要出现在重放阶段之前均有效。】==》只要出现在重放阶段之前均有效，这个应该不对吧，Verification阶段不会再有重放了吧。

**Comment by hzdavid** [comment]
谢谢提醒，文案已经修改。

**Comment by hzdavid** [comment]
Verification是在重放阶段后面执行，可以写多个。 文案已经更正。
